### ISSUE TITLE
Have you considered Click?

### ISSUE THREAD

**Issue by rogerhurwitz** [flatironinstitute/kachery#2]
I recently became acquainted with the Click [python command line interface library](https://click.palletsprojects.com/en/7.x/), and thought that it might be a good fit for kachery.  It looks like you are writing a lot of "glue" code to compensate for argarse's shortcomings that Click gives you for free (e.g., type checking, environment variable parsing, sub commands, etc.). For illustration purposes, I mocked up the attached examples.  

[kachcli.zip](https://github.com/flatironinstitute/kachery/files/3855109/kachcli.zip)

**Comment by magland** [comment]
Thanks @rogerhurwitz . This does indeed look like a better solution than argparse. I have recently simplified the interface and calling options. So once that update has been made, we can circle back and consider replacing argparse with click.

**Comment by rogerhurwitz** [comment]
Sounds good - glad to help on that if needed.  Couple of off topic thoughts:

- Is the purpose of hashing files solely for creating globally unique IDs, or is there some other reason?  If the only purpose is creating a globally unique ID have you considered the uuid standard library?  It is a much less compute intensive way of achieving the same thing.

- Cole tells me you have some thoughts in mind regarding the intersection of spikely and kachery.  Could you say more about what you are thinking?  I'm glad to help out.

Thanks,
Roger

**Comment by magland** [comment]
There are other advantages of content-determined hashes over uuids. One example: If you upload a file to a kachery database, and I upload the same file, only one copy needs to be stored. Second example: the sha1 uniquely identifies the file, and it can be verified whether I have downloaded the correct file and/or it can be verified whether I already have the correct file on my computer (so not need for download).

For the second point, we can correspond by email - or on the issue tracker of another repo.

**Comment by rogerhurwitz** [comment]
Sounds good - thanks for the clarifications.
