### ISSUE TITLE
remove method

### ISSUE THREAD

**Issue by mynameisvinn** [flatironinstitute/kachery#7]
would it make sense to include a way to remove files? perhaps something like `ka.remove(some_hash)`. 

alternatively, there could be a garbage collection mechanism.

**Comment by magland** [comment]
The problem with ka.remove(...) is that if you add the same content file twice (in two different contexts), the remove in the first context could cause problems for the second context.

So, yes, garbage collection is the answer. We are planning to implement that. However, more thought needs to go into how to determine when a file is no longer needed. That depends on the application (how kachery is being used).
